// GENERATED by scripts/derive-weapon-anchors.mjs — do not edit by hand.
//
// anchors[body][animation][directionRow][frame] = [x, y] of the weapon hand,
// or null where the hand is fully hidden that frame.
// grips[weapon] describes the resting sprite cut from that weapon's own art:
// draw each half's `rect` from its source sheet at (anchor + offset).

export type HandAnchor = [number, number] | null;
export type WeaponPiece = {
  /** [x, y, w, h] in 64px frame space. On an oversize source sheet, add 32 to
   *  both coordinates to reach the same pixels. */
  rect: [number, number, number, number];
  /** Added to the hand anchor to place the rect's top-left corner. */
  offset: [number, number];
};
/** The two halves of a weapon for one facing: what passes behind the body and
 *  what passes in front. Either may be absent for a given facing. */
export type WeaponGrip = {
  frame: number;
  behind: WeaponPiece | null;
  front: WeaponPiece | null;
};
export type WeaponGrips = {
  source: string[];
  oversize: boolean;
  anim: string;
  byDir: Record<string, WeaponGrip | null>;
};

export const HAND_ANCHORS: Record<string, Record<string, HandAnchor[][]>> =
{
 "male": {
  "walk": [
   [
    [
     42.9,
     46
    ],
    [
     43,
     46
    ],
    [
     43,
     45.2
    ],
    [
     42.7,
     45
    ],
    [
     43,
     45.2
    ],
    [
     42.9,
     46
    ],
    [
     42.9,
     46.5
    ],
    [
     41.7,
     48.5
    ],
    [
     42.9,
     46.5
    ]
   ],
   [
    [
     21,
     45.7
    ],
    [
     21,
     45.7
    ],
    [
     21.9,
     45.9
    ],
    [
     24.6,
     45.8
    ],
    [
     25.1,
     45.8
    ],
    [
     25.9,
     45.8
    ],
    [
     25,
     45.8
    ],
    [
     25,
     45.8
    ],
    [
     22.6,
     45.5
    ]
   ],
   [
    [
     42.8,
     47.2
    ],
    [
     42.8,
     47.2
    ],
    [
     42.9,
     46.4
    ],
    [
     42.9,
     46.3
    ],
    [
     42.9,
     46.4
    ],
    [
     42.8,
     47.3
    ],
    [
     42.8,
     47.7
    ],
    [
     42.5,
     48.4
    ],
    [
     42.8,
     47.7
    ]
   ],
   [
    [
     42,
     45.7
    ],
    [
     42,
     45.7
    ],
    [
     41.1,
     45.9
    ],
    [
     38.4,
     45.8
    ],
    [
     37.9,
     45.8
    ],
    [
     37.1,
     45.8
    ],
    [
     38,
     45.8
    ],
    [
     38,
     45.8
    ],
    [
     40.4,
     45.5
    ]
   ]
  ],
  "run": [
   [
    [
     44.9,
     48
    ],
    [
     45.5,
     49
    ],
    [
     41.9,
     45.5
    ],
    [
     41.9,
     44.6
    ],
    [
     41.9,
     45.5
    ],
    [
     41.9,
     46
    ],
    [
     41.9,
     45.5
    ],
    [
     41.9,
     44.6
    ]
   ],
   [
    [
     20.1,
     44.4
    ],
    [
     21.9,
     45.8
    ],
    [
     24.4,
     47
    ],
    [
     27,
     44.7
    ],
    [
     26,
     45.7
    ],
    [
     24.6,
     46.9
    ],
    [
     23.7,
     47.1
    ],
    [
     20.7,
     44.8
    ]
   ],
   [
    [
     40.9,
     47.1
    ],
    [
     42.2,
     48.1
    ],
    [
     42.8,
     47.6
    ],
    [
     43.4,
     46.3
    ],
    [
     44,
     46.7
    ],
    [
     43.9,
     47.7
    ],
    [
     43.8,
     47.3
    ],
    [
     41.6,
     46.7
    ]
   ],
   [
    [
     42.9,
     44.4
    ],
    [
     41.1,
     45.8
    ],
    [
     38.6,
     47
    ],
    [
     36,
     44.7
    ],
    [
     37,
     45.7
    ],
    [
     38.4,
     46.9
    ],
    [
     39.3,
     47.1
    ],
    [
     42.3,
     44.8
    ]
   ]
  ],
  "idle": [
   [
    [
     42.8,
     46.2
    ],
    [
     42.8,
     46
    ]
   ],
   [
    [
     23.6,
     45.8
    ],
    [
     23.6,
     45.7
    ]
   ],
   [
    [
     42.9,
     47.2
    ],
    [
     42.8,
     47.1
    ]
   ],
   [
    [
     39.4,
     45.8
    ],
    [
     39.5,
     45.7
    ]
   ]
  ],
  "spellcast": [
   [
    [
     42.8,
     46.1
    ],
    [
     42.8,
     46.1
    ],
    [
     42.8,
     46.1
    ],
    [
     42.8,
     46.1
    ],
    [
     42.8,
     46.1
    ],
    [
     42.8,
     46.1
    ],
    [
     42.8,
     46.1
    ]
   ],
   [
    [
     24.1,
     48.1
    ],
    [
     23.7,
     47.8
    ],
    [
     25.7,
     47.6
    ],
    [
     23.3,
     46
    ],
    [
     22.4,
     44.2
    ],
    [
     22.5,
     40.7
    ],
    [
     23.3,
     46
    ]
   ],
   [
    [
     42.7,
     48.7
    ],
    [
     42.6,
     47.4
    ],
    [
     39.1,
     46.5
    ],
    [
     43.9,
     46.7
    ],
    [
     43.9,
     46.7
    ],
    [
     43.9,
     46.7
    ],
    [
     43.5,
     47.6
    ]
   ],
   [
    [
     38.9,
     48.1
    ],
    [
     39.3,
     47.8
    ],
    [
     37.3,
     47.6
    ],
    [
     39.7,
     46
    ],
    [
     40.6,
     44.2
    ],
    [
     40.5,
     40.7
    ],
    [
     39.7,
     46
    ]
   ]
  ],
  "shoot": [
   [
    [
     43.9,
     46.1
    ],
    [
     43.9,
     46.1
    ],
    [
     43.9,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ],
    [
     42.4,
     46.1
    ]
   ],
   [
    [
     24.5,
     49
    ],
    [
     24.5,
     49
    ],
    [
     24.5,
     49
    ],
    [
     23.6,
     48.1
    ],
    [
     23.3,
     45
    ],
    [
     23,
     44.1
    ],
    [
     23,
     43.2
    ],
    [
     23.4,
     43.6
    ],
    [
     23.3,
     44.5
    ],
    [
     23.3,
     45
    ],
    [
     23.3,
     45
    ],
    [
     23.3,
     45
    ],
    [
     23.3,
     45
    ]
   ],
   [
    [
     47.2,
     48.6
    ],
    [
     44.5,
     48
    ],
    [
     44.1,
     48
    ],
    [
     43.1,
     48.4
    ],
    [
     42.2,
     47.3
    ],
    [
     41.1,
     45.6
    ],
    [
     41.1,
     45.1
    ],
    [
     42.8,
     46
    ],
    [
     42.4,
     47.3
    ],
    [
     42.3,
     47.3
    ],
    [
     42.4,
     47.3
    ],
    [
     41,
     47.1
    ],
    [
     42.3,
     47.3
    ]
   ],
   [
    [
     38.5,
     49
    ],
    [
     38.5,
     49
    ],
    [
     38.5,
     49
    ],
    [
     39.4,
     48.1
    ],
    [
     39.7,
     45
    ],
    [
     40,
     44.1
    ],
    [
     40,
     43.2
    ],
    [
     39.6,
     43.6
    ],
    [
     39.7,
     44.5
    ],
    [
     39.7,
     45
    ],
    [
     39.7,
     45
    ],
    [
     39.7,
     45
    ],
    [
     39.7,
     45
    ]
   ]
  ],
  "hurt": [
   [
    [
     41.7,
     46.2
    ],
    [
     42.7,
     46.7
    ],
    [
     42.7,
     46.7
    ],
    [
     42.7,
     46.7
    ],
    [
     43.4,
     45.2
    ],
    [
     43.4,
     45.2
    ]
   ]
  ]
 },
 "female": {
  "walk": [
   [
    [
     42.2,
     46.3
    ],
    [
     42.2,
     46.7
    ],
    [
     41.9,
     46.6
    ],
    [
     41.7,
     46.4
    ],
    [
     42.2,
     46.3
    ],
    [
     42.1,
     46.8
    ],
    [
     41.7,
     47.2
    ],
    [
     41.7,
     47.2
    ],
    [
     41.7,
     47.2
    ]
   ],
   [
    [
     21.3,
     47.6
    ],
    [
     21.3,
     47.6
    ],
    [
     22.6,
     47.6
    ],
    [
     25,
     47.5
    ],
    [
     25.8,
     47.2
    ],
    [
     26.3,
     47.4
    ],
    [
     25.8,
     47.2
    ],
    [
     24.9,
     47.7
    ],
    [
     23.1,
     47.7
    ]
   ],
   [
    [
     42.1,
     47.2
    ],
    [
     42.1,
     47.2
    ],
    [
     42,
     47
    ],
    [
     41.8,
     47.2
    ],
    [
     42,
     47
    ],
    [
     42.1,
     47.2
    ],
    [
     41.6,
     47.6
    ],
    [
     41.1,
     47.7
    ],
    [
     42.1,
     47.4
    ]
   ],
   [
    [
     41.7,
     47.6
    ],
    [
     41.7,
     47.6
    ],
    [
     40.4,
     47.6
    ],
    [
     38,
     47.5
    ],
    [
     37.2,
     47.2
    ],
    [
     36.7,
     47.4
    ],
    [
     37.2,
     47.2
    ],
    [
     38.1,
     47.7
    ],
    [
     39.9,
     47.7
    ]
   ]
  ],
  "run": [
   [
    [
     42.1,
     46.8
    ],
    [
     42.2,
     47.3
    ],
    [
     41.9,
     46.8
    ],
    [
     41.9,
     46
    ],
    [
     41.8,
     46.8
    ],
    [
     41.7,
     47.3
    ],
    [
     41.9,
     46.8
    ],
    [
     41.9,
     46
    ]
   ],
   [
    [
     23.2,
     46.5
    ],
    [
     25,
     47.9
    ],
    [
     24.5,
     48.9
    ],
    [
     23.2,
     46.1
    ],
    [
     22.3,
     46.5
    ],
    [
     24,
     48.2
    ],
    [
     26.2,
     49
    ],
    [
     23.6,
     47
    ]
   ],
   [
    [
     39.8,
     47.5
    ],
    [
     40.8,
     49
    ],
    [
     41.8,
     47.7
    ],
    [
     42.9,
     45.9
    ],
    [
     42.9,
     46.5
    ],
    [
     43.1,
     47.6
    ],
    [
     42.7,
     47.6
    ],
    [
     41,
     46.4
    ]
   ],
   [
    [
     39.8,
     46.5
    ],
    [
     38,
     47.9
    ],
    [
     38.5,
     48.9
    ],
    [
     39.8,
     46.1
    ],
    [
     40.7,
     46.5
    ],
    [
     39,
     48.2
    ],
    [
     36.8,
     49
    ],
    [
     39.4,
     47
    ]
   ]
  ],
  "idle": [
   [
    [
     42,
     46.8
    ],
    [
     41.8,
     46.6
    ]
   ],
   [
    [
     24,
     47.5
    ],
    [
     24,
     47.5
    ]
   ],
   [
    [
     41.9,
     47.4
    ],
    [
     41.9,
     47.2
    ]
   ],
   [
    [
     39,
     47.5
    ],
    [
     39,
     47.5
    ]
   ]
  ],
  "spellcast": [
   [
    [
     41.9,
     46.7
    ],
    [
     41.9,
     46.7
    ],
    [
     41.9,
     46.7
    ],
    [
     41.9,
     46.7
    ],
    [
     41.9,
     46.7
    ],
    [
     41.9,
     46.7
    ],
    [
     41.9,
     46.7
    ]
   ],
   [
    [
     24.8,
     49.4
    ],
    [
     24.4,
     49.1
    ],
    [
     24.8,
     48.5
    ],
    [
     23.9,
     47.7
    ],
    [
     23,
     45.1
    ],
    [
     23,
     45.1
    ],
    [
     23.9,
     47.7
    ]
   ],
   [
    [
     41,
     49.8
    ],
    [
     41,
     48.4
    ],
    [
     37.9,
     47.6
    ],
    [
     41.8,
     48
    ],
    [
     44.8,
     44.5
    ],
    [
     44.8,
     44.5
    ],
    [
     41.8,
     48
    ]
   ],
   [
    [
     38.2,
     49.4
    ],
    [
     38.5,
     49.1
    ],
    [
     38.4,
     48.6
    ],
    [
     39,
     47.7
    ],
    [
     39.9,
     45.1
    ],
    [
     39.9,
     45.1
    ],
    [
     39,
     47.7
    ]
   ]
  ],
  "shoot": [
   [
    [
     42.5,
     50.3
    ],
    [
     42.5,
     50.3
    ],
    [
     42.5,
     50.3
    ],
    [
     42.5,
     50.3
    ],
    [
     41.5,
     45.2
    ],
    [
     41.5,
     45.2
    ],
    [
     41.5,
     45.2
    ],
    [
     41.5,
     45.2
    ],
    [
     42.2,
     43.5
    ],
    [
     41.7,
     45.5
    ],
    [
     41.7,
     45.5
    ],
    [
     41.7,
     45.5
    ],
    [
     41.7,
     45.5
    ]
   ],
   [
    [
     24.9,
     50.7
    ],
    [
     24.9,
     50.7
    ],
    [
     24.9,
     50.7
    ],
    [
     24,
     49.8
    ],
    [
     23.8,
     46.7
    ],
    [
     23.3,
     45.8
    ],
    [
     23.3,
     44.9
    ],
    [
     23.8,
     45.3
    ],
    [
     23.8,
     46.3
    ],
    [
     23.8,
     46.7
    ],
    [
     23.8,
     46.7
    ],
    [
     23.8,
     46.7
    ],
    [
     23.8,
     46.7
    ]
   ],
   [
    [
     45.7,
     48.6
    ],
    [
     43.5,
     47.9
    ],
    [
     43,
     47.9
    ],
    [
     42.2,
     48.4
    ],
    [
     41.3,
     47.4
    ],
    [
     40,
     45.5
    ],
    [
     41.4,
     46.5
    ],
    [
     41.8,
     45.9
    ],
    [
     41.5,
     47.4
    ],
    [
     41.4,
     47.3
    ],
    [
     41.3,
     47.3
    ],
    [
     39.9,
     47.1
    ],
    [
     41.3,
     47.3
    ]
   ],
   [
    [
     38.1,
     50.7
    ],
    [
     38.1,
     50.7
    ],
    [
     38.1,
     50.7
    ],
    [
     39,
     49.8
    ],
    [
     39.2,
     46.7
    ],
    [
     39.7,
     45.8
    ],
    [
     39.7,
     44.9
    ],
    [
     39.2,
     45.3
    ],
    [
     39.2,
     46.3
    ],
    [
     39.2,
     46.7
    ],
    [
     39.2,
     46.7
    ],
    [
     39.2,
     46.7
    ],
    [
     39.2,
     46.7
    ]
   ]
  ],
  "hurt": [
   [
    [
     41.1,
     46.8
    ],
    [
     41.5,
     47.4
    ],
    [
     41.5,
     47.4
    ],
    [
     41.5,
     47.4
    ],
    [
     43,
     45.8
    ],
    [
     43,
     45.8
    ]
   ]
  ]
 }
};

export const WEAPON_GRIPS: Record<string, WeaponGrips> =
{
 "apprentice_staff": {
  "source": [
   "weapon/magic/simple/background/simple",
   "weapon/magic/simple/foreground/simple"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      42,
      24,
      4,
      18
     ],
     "offset": [
      -0.7,
      -22.1
     ]
    },
    "front": {
     "rect": [
      42,
      46,
      3,
      10
     ],
     "offset": [
      -0.7,
      -0.1
     ]
    }
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      18,
      27,
      9,
      36
     ],
     "offset": [
      -5.6,
      -18.8
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": null,
    "front": {
     "rect": [
      36,
      26,
      9,
      36
     ],
     "offset": [
      -6.8,
      -21.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      37,
      27,
      9,
      36
     ],
     "offset": [
      -2.4,
      -18.8
     ]
    },
    "front": null
   }
  }
 },
 "gnarled_staff": {
  "source": [
   "weapon/magic/gnarled/universal/background/gnarled",
   "weapon/magic/gnarled/universal/foreground/gnarled"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      37,
      24,
      12,
      19
     ],
     "offset": [
      -5.7,
      -22.1
     ]
    },
    "front": {
     "rect": [
      41,
      46,
      6,
      10
     ],
     "offset": [
      -1.7,
      -0.1
     ]
    }
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      18,
      28,
      12,
      32
     ],
     "offset": [
      -5.6,
      -17.8
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": null,
    "front": {
     "rect": [
      37,
      28,
      12,
      32
     ],
     "offset": [
      -5.8,
      -19.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      34,
      28,
      12,
      32
     ],
     "offset": [
      -5.4,
      -17.8
     ]
    },
    "front": null
   }
  }
 },
 "archmage_staff": {
  "source": [
   "weapon/magic/crystal/universal/background/purple",
   "weapon/magic/crystal/universal/foreground/purple"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      40,
      25,
      5,
      10
     ],
     "offset": [
      -2.7,
      -21.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      21,
      26,
      5,
      10
     ],
     "offset": [
      -2.6,
      -19.8
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": null,
    "front": {
     "rect": [
      41,
      26,
      5,
      10
     ],
     "offset": [
      -1.8,
      -21.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      38,
      26,
      5,
      10
     ],
     "offset": [
      -1.4,
      -19.8
     ]
    },
    "front": null
   }
  }
 },
 "short_bow": {
  "source": [
   "weapon/ranged/bow/normal/walk/background/normal",
   "weapon/ranged/bow/normal/walk/foreground/normal"
  ],
  "oversize": true,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      29,
      26,
      35,
      27
     ],
     "offset": [
      -12.9,
      -20.7
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      8,
      28,
      43,
      23
     ],
     "offset": [
      -16,
      -19.5
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      37,
      26,
      22,
      24
     ],
     "offset": [
      -4.9,
      -21.3
     ]
    },
    "front": {
     "rect": [
      19,
      37,
      25,
      16
     ],
     "offset": [
      -22.9,
      -10.3
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      14,
      28,
      43,
      23
     ],
     "offset": [
      -25,
      -19.5
     ]
    },
    "front": null
   }
  }
 },
 "war_bow": {
  "source": [
   "weapon/ranged/bow/recurve/walk/background/recurve",
   "weapon/ranged/bow/recurve/walk/foreground/recurve"
  ],
  "oversize": true,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      25,
      25,
      39,
      29
     ],
     "offset": [
      -16.9,
      -21.7
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      4,
      30,
      45,
      24
     ],
     "offset": [
      -20,
      -17.5
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      40,
      27,
      18,
      23
     ],
     "offset": [
      -1.9,
      -20.3
     ]
    },
    "front": {
     "rect": [
      17,
      35,
      27,
      22
     ],
     "offset": [
      -24.9,
      -12.3
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      15,
      30,
      45,
      24
     ],
     "offset": [
      -24,
      -17.5
     ]
    },
    "front": null
   }
  }
 },
 "great_bow": {
  "source": [
   "weapon/ranged/bow/great/walk/background/great",
   "weapon/ranged/bow/great/walk/foreground/great"
  ],
  "oversize": true,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      25,
      24,
      39,
      30
     ],
     "offset": [
      -16.9,
      -22.7
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      2,
      29,
      51,
      24
     ],
     "offset": [
      -22,
      -18.5
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      43,
      25,
      18,
      24
     ],
     "offset": [
      1.1,
      -22.3
     ]
    },
    "front": {
     "rect": [
      14,
      36,
      29,
      20
     ],
     "offset": [
      -27.9,
      -11.3
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      12,
      29,
      51,
      24
     ],
     "offset": [
      -27,
      -18.5
     ]
    },
    "front": null
   }
  }
 }
};
