// GENERATED by scripts/derive-weapon-anchors.mjs — do not edit by hand.
//
// anchors[body][animation][directionRow][frame] = [x, y] of the weapon hand,
// or null where the hand is fully hidden that frame.
// grips[weapon] describes the resting sprite cut from that weapon's own art:
// draw each half's `rect` from its source sheet at (anchor + offset).

export type HandAnchor = [number, number] | null;
export type WeaponPiece = {
  /** [x, y, w, h] in 64px frame space. On an oversize source sheet, add 32 to
   *  both coordinates to reach the same pixels. */
  rect: [number, number, number, number];
  /** Added to the hand anchor to place the rect's top-left corner. */
  offset: [number, number];
};
/** The two halves of a weapon for one facing: what passes behind the body and
 *  what passes in front. Either may be absent for a given facing. */
export type WeaponGrip = {
  frame: number;
  behind: WeaponPiece | null;
  front: WeaponPiece | null;
};
export type WeaponGrips = {
  source: string[];
  oversize: boolean;
  anim: string;
  byDir: Record<string, WeaponGrip | null>;
};

export const HAND_ANCHORS: Record<string, Record<string, HandAnchor[][]>> =
{
 "male": {
  "walk": [
   [
    [
     42.8,
     46.1
    ],
    [
     42.9,
     46
    ],
    [
     42.9,
     44.3
    ],
    [
     42.3,
     43.8
    ],
    [
     42.9,
     44.4
    ],
    [
     42.7,
     46.2
    ],
    [
     42.7,
     47.2
    ],
    [
     40.2,
     51.7
    ],
    [
     42.7,
     47.2
    ]
   ],
   [
    [
     32.9,
     48.1
    ],
    [
     32.9,
     48.1
    ],
    [
     34.9,
     48.4
    ],
    [
     40.9,
     48.3
    ],
    [
     42,
     48.2
    ],
    [
     43.9,
     48.3
    ],
    [
     41.9,
     48.3
    ],
    [
     41.9,
     48.3
    ],
    [
     36.5,
     47.6
    ]
   ],
   [
    [
     42.8,
     47.2
    ],
    [
     42.8,
     47.2
    ],
    [
     42.9,
     45.4
    ],
    [
     42.9,
     45.1
    ],
    [
     43,
     45.3
    ],
    [
     42.8,
     47.3
    ],
    [
     42.8,
     48.3
    ],
    [
     42.1,
     49.9
    ],
    [
     42.8,
     48.3
    ]
   ],
   [
    [
     30.1,
     48.1
    ],
    [
     30.1,
     48.1
    ],
    [
     28.1,
     48.4
    ],
    [
     22.1,
     48.3
    ],
    [
     21,
     48.2
    ],
    [
     19.1,
     48.3
    ],
    [
     21.1,
     48.3
    ],
    [
     21.1,
     48.3
    ],
    [
     26.5,
     47.6
    ]
   ]
  ],
  "run": [
   [
    [
     38,
     39.5
    ],
    [
     39.4,
     41.7
    ],
    [
     39.4,
     41.7
    ],
    [
     39.4,
     41.7
    ],
    [
     39.4,
     41.7
    ],
    [
     39.4,
     41.7
    ],
    [
     38.8,
     41.9
    ],
    [
     39,
     38.5
    ]
   ],
   [
    [
     21.2,
     39.8
    ],
    [
     25.3,
     42.9
    ],
    [
     30.9,
     45.7
    ],
    [
     36.6,
     40.5
    ],
    [
     34.4,
     42.7
    ],
    [
     31.4,
     45.4
    ],
    [
     29.3,
     45.8
    ],
    [
     22.7,
     40.8
    ]
   ],
   [
    [
     34.4,
     44.4
    ],
    [
     37.3,
     46.8
    ],
    [
     38.6,
     45.6
    ],
    [
     39.8,
     42.7
    ],
    [
     41.1,
     43.6
    ],
    [
     41,
     45.9
    ],
    [
     40.7,
     44.9
    ],
    [
     35.8,
     43.5
    ]
   ],
   [
    [
     41.8,
     39.8
    ],
    [
     37.7,
     42.9
    ],
    [
     32.1,
     45.7
    ],
    [
     26.4,
     40.5
    ],
    [
     28.6,
     42.7
    ],
    [
     31.6,
     45.4
    ],
    [
     33.7,
     45.8
    ],
    [
     40.3,
     40.8
    ]
   ]
  ],
  "idle": [
   [
    [
     42.8,
     47.2
    ],
    [
     42.8,
     46.7
    ]
   ],
   [
    [
     23.6,
     45.8
    ],
    [
     23.6,
     45.5
    ]
   ],
   [
    [
     42.8,
     47.2
    ],
    [
     42.6,
     47
    ]
   ],
   [
    [
     39.2,
     45.7
    ],
    [
     39.4,
     45.5
    ]
   ]
  ],
  "spellcast": [
   [
    [
     42.8,
     47.1
    ],
    [
     42,
     45.2
    ],
    [
     42,
     45.2
    ],
    [
     47.7,
     40.6
    ],
    [
     53.4,
     34.5
    ],
    [
     51.9,
     27.9
    ],
    [
     47.7,
     40.6
    ]
   ],
   [
    [
     23.6,
     45.5
    ],
    [
     22.7,
     44.9
    ],
    [
     27.2,
     44.3
    ],
    [
     21.8,
     40.9
    ],
    [
     19.8,
     36.8
    ],
    [
     20.2,
     29.1
    ],
    [
     21.8,
     40.9
    ]
   ],
   [
    [
     42.8,
     47
    ],
    [
     42.6,
     44
    ],
    [
     34.9,
     42.2
    ],
    [
     45.6,
     42.5
    ],
    [
     53.2,
     33.8
    ],
    [
     51.8,
     27.3
    ],
    [
     44.6,
     44.5
    ]
   ],
   [
    [
     39.4,
     45.5
    ],
    [
     40.3,
     44.9
    ],
    [
     35.8,
     44.3
    ],
    [
     41.2,
     40.9
    ],
    [
     43.2,
     36.8
    ],
    [
     42.8,
     29.1
    ],
    [
     41.2,
     40.9
    ]
   ]
  ],
  "shoot": [
   [
    [
     41.9,
     47
    ],
    [
     41.7,
     50.9
    ],
    [
     41.7,
     50.9
    ],
    [
     39.8,
     39
    ],
    [
     38.6,
     36.1
    ],
    [
     38.6,
     36.1
    ],
    [
     38.6,
     36.1
    ],
    [
     38.6,
     36.1
    ],
    [
     39.8,
     32.6
    ],
    [
     39,
     36.9
    ],
    [
     39.8,
     39
    ],
    [
     39.8,
     39
    ],
    [
     39.9,
     39.3
    ]
   ],
   [
    [
     24.6,
     45.5
    ],
    [
     22.7,
     45.9
    ],
    [
     18.3,
     44
    ],
    [
     16.3,
     42.1
    ],
    [
     15.7,
     35.1
    ],
    [
     15,
     33.1
    ],
    [
     14.9,
     31.1
    ],
    [
     15.8,
     32.1
    ],
    [
     15.7,
     34.2
    ],
    [
     15.7,
     35.1
    ],
    [
     15.7,
     35.1
    ],
    [
     15.7,
     35.1
    ],
    [
     15.7,
     35.1
    ]
   ],
   [
    [
     41.8,
     47
    ],
    [
     35.9,
     45.6
    ],
    [
     34.9,
     45.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ],
    [
     32.8,
     46.6
    ]
   ],
   [
    [
     38.4,
     45.5
    ],
    [
     40.3,
     45.9
    ],
    [
     44.7,
     44
    ],
    [
     46.7,
     42.1
    ],
    [
     47.3,
     35.1
    ],
    [
     48.1,
     33.1
    ],
    [
     48.1,
     31.1
    ],
    [
     47.2,
     32.1
    ],
    [
     47.3,
     34.2
    ],
    [
     47.3,
     35.1
    ],
    [
     47.3,
     35.1
    ],
    [
     47.3,
     35.1
    ],
    [
     47.3,
     35.1
    ]
   ]
  ],
  "hurt": [
   [
    [
     42.8,
     47.2
    ],
    [
     44.9,
     48.3
    ],
    [
     44.9,
     48.3
    ],
    [
     44.9,
     48.3
    ],
    [
     46.5,
     44.9
    ],
    [
     46.5,
     44.9
    ]
   ]
  ],
  "slash": [
   [
    [
     42.8,
     47.2
    ],
    [
     42.8,
     47.2
    ],
    [
     42.8,
     47.2
    ],
    [
     42.8,
     47.2
    ],
    [
     50.1,
     31.3
    ],
    [
     53.1,
     35.7
    ]
   ],
   [
    [
     23.6,
     45.8
    ],
    [
     19.7,
     48.1
    ],
    [
     22.7,
     46.5
    ],
    [
     14.5,
     44
    ],
    [
     10.9,
     33
    ],
    [
     13.8,
     32.2
    ]
   ],
   [
    [
     42.8,
     47.2
    ],
    [
     37.1,
     46
    ],
    [
     37.1,
     46
    ],
    [
     39.9,
     46.5
    ],
    [
     50.9,
     43
    ],
    [
     54,
     40.1
    ]
   ],
   [
    [
     39.2,
     45.7
    ],
    [
     43.3,
     48.1
    ],
    [
     40.3,
     46.5
    ],
    [
     48.5,
     44
    ],
    [
     52.1,
     33
    ],
    [
     49.2,
     32.2
    ]
   ]
  ],
  "thrust": [
   [
    [
     42.9,
     47
    ],
    [
     42.5,
     50.7
    ],
    [
     40.3,
     49.9
    ],
    [
     40.3,
     49.9
    ],
    [
     40.3,
     49.9
    ],
    [
     40.3,
     49.9
    ],
    [
     40.3,
     49.9
    ],
    [
     40.3,
     49.9
    ]
   ],
   [
    [
     23.9,
     45.8
    ],
    [
     21.8,
     46.2
    ],
    [
     21.7,
     45.3
    ],
    [
     25.5,
     43
    ],
    [
     18.7,
     43.8
    ],
    [
     15.7,
     43.9
    ],
    [
     18.7,
     43.8
    ],
    [
     25.5,
     43
    ]
   ],
   [
    [
     42.8,
     47.2
    ],
    [
     34.9,
     46.3
    ],
    [
     34.9,
     46.3
    ],
    [
     34.9,
     46.3
    ],
    [
     34.9,
     46.3
    ],
    [
     34.9,
     46.3
    ],
    [
     34.9,
     46.3
    ],
    [
     34.9,
     46.3
    ]
   ],
   [
    [
     39.2,
     45.7
    ],
    [
     41.2,
     46.2
    ],
    [
     41.3,
     45.3
    ],
    [
     37.5,
     43
    ],
    [
     44.3,
     43.8
    ],
    [
     47.3,
     43.9
    ],
    [
     44.3,
     43.8
    ],
    [
     37.5,
     42.9
    ]
   ]
  ]
 },
 "female": {
  "walk": [
   [
    [
     41.9,
     46.7
    ],
    [
     42,
     47.6
    ],
    [
     41.3,
     47.3
    ],
    [
     40.9,
     46.8
    ],
    [
     41.9,
     46.7
    ],
    [
     41.8,
     47.8
    ],
    [
     40.9,
     48.6
    ],
    [
     40.9,
     48.6
    ],
    [
     40.9,
     48.6
    ]
   ],
   [
    [
     31.8,
     48.3
    ],
    [
     31.8,
     48.3
    ],
    [
     34.8,
     48.3
    ],
    [
     40.1,
     48.1
    ],
    [
     41.9,
     47.3
    ],
    [
     42.9,
     47.7
    ],
    [
     41.9,
     47.3
    ],
    [
     39.9,
     48.5
    ],
    [
     35.8,
     48.5
    ]
   ],
   [
    [
     41.9,
     47.3
    ],
    [
     41.9,
     47.3
    ],
    [
     41.8,
     46.8
    ],
    [
     41.3,
     47.3
    ],
    [
     41.8,
     46.9
    ],
    [
     41.9,
     47.4
    ],
    [
     40.9,
     48.3
    ],
    [
     39.8,
     48.4
    ],
    [
     41.9,
     47.7
    ]
   ],
   [
    [
     31.2,
     48.3
    ],
    [
     31.2,
     48.3
    ],
    [
     28.2,
     48.3
    ],
    [
     22.9,
     48.1
    ],
    [
     21.1,
     47.3
    ],
    [
     20.1,
     47.7
    ],
    [
     21.1,
     47.3
    ],
    [
     23.1,
     48.5
    ],
    [
     27.2,
     48.5
    ]
   ]
  ],
  "run": [
   [
    [
     31.8,
     33
    ],
    [
     32.1,
     34
    ],
    [
     31.5,
     33
    ],
    [
     31.5,
     31.2
    ],
    [
     31.2,
     33
    ],
    [
     30.9,
     34
    ],
    [
     31.5,
     33
    ],
    [
     31.5,
     31.2
    ]
   ],
   [
    [
     21.6,
     39.5
    ],
    [
     25.6,
     42.5
    ],
    [
     24.6,
     44.8
    ],
    [
     21.6,
     38.5
    ],
    [
     19.6,
     39.5
    ],
    [
     23.4,
     43.2
    ],
    [
     28.2,
     45.1
    ],
    [
     22.6,
     40.5
    ]
   ],
   [
    [
     32.7,
     45.8
    ],
    [
     34.9,
     49
    ],
    [
     37,
     46.2
    ],
    [
     39.4,
     42.3
    ],
    [
     39.5,
     43.5
    ],
    [
     39.9,
     45.9
    ],
    [
     39,
     45.9
    ],
    [
     35.3,
     43.3
    ]
   ],
   [
    [
     41.4,
     39.5
    ],
    [
     37.4,
     42.5
    ],
    [
     38.4,
     44.8
    ],
    [
     41.4,
     38.5
    ],
    [
     43.4,
     39.5
    ],
    [
     39.6,
     43.2
    ],
    [
     34.8,
     44.9
    ],
    [
     40.4,
     40.5
    ]
   ]
  ],
  "idle": [
   [
    [
     41.9,
     47.7
    ],
    [
     41.5,
     47.3
    ]
   ],
   [
    [
     24,
     47.5
    ],
    [
     24,
     47.5
    ]
   ],
   [
    [
     41.9,
     47.3
    ],
    [
     41.9,
     46.8
    ]
   ],
   [
    [
     39,
     47.5
    ],
    [
     39,
     47.5
    ]
   ]
  ],
  "spellcast": [
   [
    [
     41.9,
     47.7
    ],
    [
     41.9,
     47.7
    ],
    [
     41.9,
     47.7
    ],
    [
     46.8,
     40.1
    ],
    [
     50.4,
     35.3
    ],
    [
     50,
     28.8
    ],
    [
     46.6,
     40
    ]
   ],
   [
    [
     24,
     47.5
    ],
    [
     23.2,
     46.7
    ],
    [
     24.1,
     45.4
    ],
    [
     22.1,
     43.6
    ],
    [
     20.1,
     37.8
    ],
    [
     19.9,
     30.8
    ],
    [
     22.1,
     43.6
    ]
   ],
   [
    [
     41.9,
     47.3
    ],
    [
     41.9,
     44.2
    ],
    [
     35,
     42.3
    ],
    [
     43.8,
     43.3
    ],
    [
     50.4,
     35.6
    ],
    [
     49.9,
     28.8
    ],
    [
     43.8,
     43.3
    ]
   ],
   [
    [
     39,
     47.5
    ],
    [
     39.8,
     46.7
    ],
    [
     39.4,
     45.6
    ],
    [
     40.9,
     43.6
    ],
    [
     42.9,
     37.8
    ],
    [
     43.1,
     30.8
    ],
    [
     40.9,
     43.6
    ]
   ]
  ],
  "shoot": [
   [
    [
     40.9,
     47.7
    ],
    [
     40.9,
     50.7
    ],
    [
     40.9,
     50.7
    ],
    [
     40.9,
     50.7
    ],
    [
     38.7,
     36.2
    ],
    [
     38.7,
     36.2
    ],
    [
     38.7,
     36.2
    ],
    [
     38.7,
     36.2
    ],
    [
     40.1,
     32.5
    ],
    [
     39.1,
     36.9
    ],
    [
     39.1,
     36.9
    ],
    [
     39.1,
     36.9
    ],
    [
     39.1,
     36.9
    ]
   ],
   [
    [
     25,
     47.5
    ],
    [
     22.7,
     45.9
    ],
    [
     18.1,
     44.1
    ],
    [
     16.2,
     42
    ],
    [
     15.7,
     35.1
    ],
    [
     14.7,
     33.2
    ],
    [
     14.7,
     31.1
    ],
    [
     15.8,
     32.1
    ],
    [
     15.7,
     34.2
    ],
    [
     15.7,
     35.1
    ],
    [
     15.7,
     35.1
    ],
    [
     15.7,
     35.1
    ],
    [
     15.7,
     35.1
    ]
   ],
   [
    [
     40.9,
     47.3
    ],
    [
     35.9,
     45.6
    ],
    [
     34.9,
     45.6
    ],
    [
     33.1,
     46.8
    ],
    [
     33.1,
     46.8
    ],
    [
     33.1,
     46.8
    ],
    [
     33.1,
     46.8
    ],
    [
     32.2,
     41.2
    ],
    [
     32.2,
     41.2
    ],
    [
     32.2,
     41.2
    ],
    [
     32.2,
     41.2
    ],
    [
     32.2,
     41.2
    ],
    [
     32.2,
     41.2
    ]
   ],
   [
    [
     38,
     47.5
    ],
    [
     40.3,
     45.9
    ],
    [
     44.9,
     44.1
    ],
    [
     46.8,
     42
    ],
    [
     47.3,
     35.1
    ],
    [
     48.3,
     33.2
    ],
    [
     48.3,
     31.1
    ],
    [
     47.2,
     32.1
    ],
    [
     47.3,
     34.2
    ],
    [
     47.3,
     35.1
    ],
    [
     47.3,
     35.1
    ],
    [
     47.3,
     35.1
    ],
    [
     47.3,
     35.1
    ]
   ]
  ],
  "hurt": [
   [
    [
     41.9,
     47.3
    ],
    [
     42.8,
     48.6
    ],
    [
     42.8,
     48.6
    ],
    [
     42.8,
     48.6
    ],
    [
     46,
     45
    ],
    [
     46,
     45
    ]
   ]
  ],
  "slash": [
   [
    [
     41.9,
     47.7
    ],
    [
     41.9,
     47.7
    ],
    [
     41.9,
     47.7
    ],
    [
     41.9,
     47.7
    ],
    [
     50.1,
     31.4
    ],
    [
     53,
     35.7
    ]
   ],
   [
    [
     24,
     47.5
    ],
    [
     19.6,
     48.3
    ],
    [
     23.7,
     48.5
    ],
    [
     15.4,
     44.1
    ],
    [
     10.8,
     32.9
    ],
    [
     14.3,
     31.7
    ]
   ],
   [
    [
     41.9,
     47.3
    ],
    [
     37.2,
     45.9
    ],
    [
     37.2,
     45.9
    ],
    [
     39.2,
     48.4
    ],
    [
     51.5,
     43.4
    ],
    [
     54.3,
     39.2
    ]
   ],
   [
    [
     39,
     47.5
    ],
    [
     43.4,
     48.3
    ],
    [
     39.3,
     48.5
    ],
    [
     47.6,
     44.1
    ],
    [
     52.2,
     32.9
    ],
    [
     48.7,
     31.7
    ]
   ]
  ],
  "thrust": [
   [
    [
     41.9,
     47.7
    ],
    [
     40.9,
     50.7
    ],
    [
     40.5,
     50.9
    ],
    [
     40.5,
     50.9
    ],
    [
     40.5,
     50.9
    ],
    [
     40.5,
     50.9
    ],
    [
     40.5,
     50.9
    ],
    [
     40.5,
     50.9
    ]
   ],
   [
    [
     24,
     47.5
    ],
    [
     21.7,
     45.9
    ],
    [
     21.7,
     45.2
    ],
    [
     25.5,
     43
    ],
    [
     19.6,
     43.9
    ],
    [
     16.8,
     43.9
    ],
    [
     19.6,
     43.9
    ],
    [
     25.5,
     43
    ]
   ],
   [
    [
     41.9,
     47.3
    ],
    [
     35.3,
     46.1
    ],
    [
     35.3,
     46.1
    ],
    [
     35.3,
     46.1
    ],
    [
     35.3,
     46.1
    ],
    [
     35.3,
     46.1
    ],
    [
     35.3,
     46.1
    ],
    [
     35.3,
     46.1
    ]
   ],
   [
    [
     39,
     47.5
    ],
    [
     41.3,
     45.9
    ],
    [
     41.3,
     45.2
    ],
    [
     37.5,
     43
    ],
    [
     43.4,
     43.9
    ],
    [
     46.2,
     43.9
    ],
    [
     43.4,
     43.9
    ],
    [
     37.5,
     43
    ]
   ]
  ]
 }
};

export const WEAPON_GRIPS: Record<string, WeaponGrips> =
{
 "apprentice_staff": {
  "source": [
   "weapon/magic/simple/background/simple",
   "weapon/magic/simple/foreground/simple"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      42,
      24,
      4,
      18
     ],
     "offset": [
      -0.8,
      -22.1
     ]
    },
    "front": {
     "rect": [
      42,
      46,
      3,
      10
     ],
     "offset": [
      -0.8,
      -0.1
     ]
    }
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      18,
      27,
      9,
      36
     ],
     "offset": [
      -14.9,
      -21.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": null,
    "front": {
     "rect": [
      36,
      26,
      9,
      36
     ],
     "offset": [
      -6.8,
      -21.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      37,
      27,
      9,
      36
     ],
     "offset": [
      6.9,
      -21.1
     ]
    },
    "front": null
   }
  }
 },
 "gnarled_staff": {
  "source": [
   "weapon/magic/gnarled/universal/background/gnarled",
   "weapon/magic/gnarled/universal/foreground/gnarled"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      37,
      24,
      12,
      19
     ],
     "offset": [
      -5.8,
      -22.1
     ]
    },
    "front": {
     "rect": [
      41,
      46,
      6,
      10
     ],
     "offset": [
      -1.8,
      -0.1
     ]
    }
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      18,
      28,
      12,
      32
     ],
     "offset": [
      -14.9,
      -20.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": null,
    "front": {
     "rect": [
      37,
      28,
      12,
      32
     ],
     "offset": [
      -5.8,
      -19.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      34,
      28,
      12,
      32
     ],
     "offset": [
      3.9,
      -20.1
     ]
    },
    "front": null
   }
  }
 },
 "archmage_staff": {
  "source": [
   "weapon/magic/crystal/universal/background/purple",
   "weapon/magic/crystal/universal/foreground/purple"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      40,
      25,
      5,
      10
     ],
     "offset": [
      -2.8,
      -21.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      21,
      26,
      5,
      10
     ],
     "offset": [
      -11.9,
      -22.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": null,
    "front": {
     "rect": [
      41,
      26,
      5,
      10
     ],
     "offset": [
      -1.8,
      -21.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      38,
      26,
      5,
      10
     ],
     "offset": [
      7.9,
      -22.1
     ]
    },
    "front": null
   }
  }
 },
 "short_bow": {
  "source": [
   "weapon/ranged/bow/normal/universal/background/normal",
   "weapon/ranged/bow/normal/universal/foreground/normal"
  ],
  "oversize": false,
  "anim": "shoot",
  "byDir": {
   "up": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      25,
      4,
      7,
      13
     ],
     "offset": [
      -14.1,
      -32.9
     ]
    }
   },
   "left": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      14,
      11,
      16,
      44
     ],
     "offset": [
      -1.7,
      -24.1
     ]
    }
   },
   "down": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      27,
      20,
      7,
      44
     ],
     "offset": [
      -5.2,
      -21.2
     ]
    }
   },
   "right": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      34,
      11,
      16,
      44
     ],
     "offset": [
      -13.3,
      -24.1
     ]
    }
   }
  }
 },
 "war_bow": {
  "source": [
   "weapon/ranged/bow/recurve/universal/background/recurve",
   "weapon/ranged/bow/recurve/universal/foreground/recurve"
  ],
  "oversize": false,
  "anim": "shoot",
  "byDir": {
   "up": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      24,
      5,
      7,
      12
     ],
     "offset": [
      -15.1,
      -31.9
     ]
    }
   },
   "left": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      12,
      10,
      17,
      48
     ],
     "offset": [
      -3.7,
      -25.1
     ]
    }
   },
   "down": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      26,
      19,
      9,
      44
     ],
     "offset": [
      -6.2,
      -22.2
     ]
    }
   },
   "right": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      35,
      10,
      17,
      48
     ],
     "offset": [
      -12.3,
      -25.1
     ]
    }
   }
  }
 },
 "great_bow": {
  "source": [
   "weapon/ranged/bow/great/universal/background/great",
   "weapon/ranged/bow/great/universal/foreground/great"
  ],
  "oversize": false,
  "anim": "shoot",
  "byDir": {
   "up": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      25,
      2,
      7,
      15
     ],
     "offset": [
      -14.1,
      -34.9
     ]
    }
   },
   "left": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      13,
      9,
      17,
      52
     ],
     "offset": [
      -2.7,
      -26.1
     ]
    }
   },
   "down": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      25,
      12,
      10,
      52
     ],
     "offset": [
      -7.2,
      -29.2
     ]
    }
   },
   "right": {
    "frame": 9,
    "behind": null,
    "front": {
     "rect": [
      34,
      9,
      17,
      52
     ],
     "offset": [
      -13.3,
      -26.1
     ]
    }
   }
  }
 },
 "iron_spear": {
  "source": [
   "weapon/polearm/spear/background/iron",
   "weapon/polearm/spear/foreground/iron"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      7,
      34,
      51,
      19
     ],
     "offset": [
      -35.8,
      -12.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      3,
      36,
      51,
      19
     ],
     "offset": [
      -29.9,
      -12.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      46,
      40,
      17,
      8
     ],
     "offset": [
      3.2,
      -7.2
     ]
    },
    "front": {
     "rect": [
      12,
      47,
      30,
      12
     ],
     "offset": [
      -30.8,
      -0.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      10,
      36,
      51,
      19
     ],
     "offset": [
      -20.1,
      -12.1
     ]
    },
    "front": null
   }
  }
 },
 "war_spear": {
  "source": [
   "weapon/polearm/spear/background/steel",
   "weapon/polearm/spear/foreground/steel"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      7,
      34,
      51,
      19
     ],
     "offset": [
      -35.8,
      -12.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      3,
      36,
      51,
      19
     ],
     "offset": [
      -29.9,
      -12.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      46,
      40,
      17,
      8
     ],
     "offset": [
      3.2,
      -7.2
     ]
    },
    "front": {
     "rect": [
      12,
      47,
      30,
      12
     ],
     "offset": [
      -30.8,
      -0.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      10,
      36,
      51,
      19
     ],
     "offset": [
      -20.1,
      -12.1
     ]
    },
    "front": null
   }
  }
 },
 "champion_spear": {
  "source": [
   "weapon/polearm/spear/background/gold",
   "weapon/polearm/spear/foreground/gold"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      7,
      34,
      51,
      19
     ],
     "offset": [
      -35.8,
      -12.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      3,
      36,
      51,
      19
     ],
     "offset": [
      -29.9,
      -12.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      46,
      40,
      17,
      8
     ],
     "offset": [
      3.2,
      -7.2
     ]
    },
    "front": {
     "rect": [
      12,
      47,
      30,
      12
     ],
     "offset": [
      -30.8,
      -0.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      10,
      36,
      51,
      19
     ],
     "offset": [
      -20.1,
      -12.1
     ]
    },
    "front": null
   }
  }
 },
 "boar_spear": {
  "source": [
   "weapon/polearm/spear/background/dark",
   "weapon/polearm/spear/foreground/dark"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      7,
      34,
      51,
      19
     ],
     "offset": [
      -35.8,
      -12.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      3,
      36,
      51,
      19
     ],
     "offset": [
      -29.9,
      -12.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      46,
      40,
      17,
      8
     ],
     "offset": [
      3.2,
      -7.2
     ]
    },
    "front": {
     "rect": [
      12,
      47,
      30,
      12
     ],
     "offset": [
      -30.8,
      -0.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      10,
      36,
      51,
      19
     ],
     "offset": [
      -20.1,
      -12.1
     ]
    },
    "front": null
   }
  }
 },
 "bronze_spear": {
  "source": [
   "weapon/polearm/spear/background/bronze",
   "weapon/polearm/spear/foreground/bronze"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      7,
      34,
      51,
      19
     ],
     "offset": [
      -35.8,
      -12.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      3,
      36,
      51,
      19
     ],
     "offset": [
      -29.9,
      -12.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      46,
      40,
      17,
      8
     ],
     "offset": [
      3.2,
      -7.2
     ]
    },
    "front": {
     "rect": [
      12,
      47,
      30,
      12
     ],
     "offset": [
      -30.8,
      -0.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      10,
      36,
      51,
      19
     ],
     "offset": [
      -20.1,
      -12.1
     ]
    },
    "front": null
   }
  }
 },
 "serpent_pike": {
  "source": [
   "weapon/polearm/spear/background/silver",
   "weapon/polearm/spear/foreground/silver"
  ],
  "oversize": false,
  "anim": "walk",
  "byDir": {
   "up": {
    "frame": 0,
    "behind": {
     "rect": [
      7,
      34,
      51,
      19
     ],
     "offset": [
      -35.8,
      -12.1
     ]
    },
    "front": null
   },
   "left": {
    "frame": 0,
    "behind": {
     "rect": [
      3,
      36,
      51,
      19
     ],
     "offset": [
      -29.9,
      -12.1
     ]
    },
    "front": null
   },
   "down": {
    "frame": 0,
    "behind": {
     "rect": [
      46,
      40,
      17,
      8
     ],
     "offset": [
      3.2,
      -7.2
     ]
    },
    "front": {
     "rect": [
      12,
      47,
      30,
      12
     ],
     "offset": [
      -30.8,
      -0.2
     ]
    }
   },
   "right": {
    "frame": 0,
    "behind": {
     "rect": [
      10,
      36,
      51,
      19
     ],
     "offset": [
      -20.1,
      -12.1
     ]
    },
    "front": null
   }
  }
 }
};
